spring:
  datasource:
    url: jdbc:h2:file:./dataTrade
    username: interview
    password: interview
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: true
  h2:
    console:
      enabled: true

server:
  port: 8008